# Generated by Django 4.1.1 on 2022-09-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=80)),
                ('organization', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('creation_date', models.DateField(max_length=80)),
            ],
        ),
    ]
